/*
*
* Copyright (C) 2008-2017 Dimension Gamers <http://www.dimensiongamers.net>
*
* File: "BuffDef.h"
*
*/

#ifndef BUFFDEF_H
#define BUFFDEF_H


#define MAX_BUFF				32

#define BUFF_LOOP(loop)			for ( int32 loop = 0; loop < MAX_BUFF; ++loop )

enum BuffNumber
{
	BUFF_GREATER_ATTACK								= 1,
	BUFF_GREATER_DEFENSE							= 2,
	BUFF_ELF_SOLDIER								= 3,
	BUFF_MANA_SHIELD								= 4,
	BUFF_INFINITY_ARROW								= 6,
	BUFF_GREATER_FORTITUDE							= 8,

	BUFF_POTION_OF_BLESS							= 10,
	BUFF_POTION_OF_SOUL								= 11,

	BUFF_CASTLE_SIEGE_GATE_STATUS					= 13,
	BUFF_CASTLE_SIEGE_DEFENSE						= 14,
	BUFF_CASTLE_SIEGE_ATTACK_1						= 15,
	BUFF_CASTLE_SIEGE_ATTACK_2						= 16,
	BUFF_CASTLE_SIEGE_ATTACK_3						= 17,

	BUFF_TRANSPARENCY								= 18,

	BUFF_CROWN_STATUS								= 20,

	BUFF_ALTAR_WOLF_CONTRACT_ENABLED				= 21,
	BUFF_ALTAR_WOLF_CONTRACT_DISABLED				= 22,
	BUFF_ALTAR_WOLF_CONTRACT_STATUS					= 23,
	BUFF_ALTAR_WOLF_CONTRACT_ATTEMPT				= 24,

	BUFF_INVISIBILITY								= 27,

	BUFF_GM_BUFF_STAT								= 29,
	BUFF_GM_BUFF_DEFENSE_ATTACK						= 30,
	BUFF_GM_BUFF_EXPERIENCE							= 31,
	BUFF_ORDER_OF_PROTECTION						= 34,

	BUFF_ADMIN										= 28,

	BUFF_SEAL_OF_ASCENSION							= 40,
	BUFF_SEAL_OF_WEALTH								= 41,
	BUFF_SEAL_OF_SUSTENANCE							= 42,
	BUFF_MASTER_SEAL_OF_ASCENSION					= 101,
	BUFF_MASTER_SEAL_OF_WEALTH						= 102,
	BUFF_PARTY_EXPERIENCE							= 112,

	BUFF_POISON										= 55,
	BUFF_ICE										= 56,
	BUFF_ICE_ARROW									= 57,
	BUFF_DEFENSIBILITY_REDUCTION					= 58,
	BUFF_STUN										= 61,
	BUFF_SLEEP										= 72,
	BUFF_COLD										= 86,

	BUFF_INMUNE_SKILL								= 63,
	BUFF_INMUNE_ATTACK								= 64,

	BUFF_RESTRICTION								= 65,

	//BUFF_REQUIEM									= 74,
	BUFF_EXPLOSION									= 75,
	BUFF_WEAKNESS									= 76,
	BUFF_INNOVATION									= 77,

	BUFF_BERSERKER									= 81,
	BUFF_FLAME_STRIKE								= 83,
	BUFF_GIGANTIC_STORM								= 84,
	BUFF_LIGHTNING_SHOCK							= 85,

	BUFF_SANTA_BLESSING_CHRISTMAS					= 91,
	BUFF_SANTA_HEALING								= 92,
	BUFF_SANTA_PROTECTION							= 93,
	BUFF_SANTA_STRENGTHENER							= 94,
	BUFF_SANTA_DEFENSE								= 95,
	BUFF_SANTA_QUICKNESS							= 96,
	BUFF_SANTA_FORTUNE								= 97,

	BUFF_DUEL_WATCHER								= 98,

	BUFF_TALISMAN_OF_GUARDIAN						= 99,
	BUFF_TALISMAN_OF_ITEM_PROTECTION				= 100,

	BUFF_DECREASE_DEFENSE_SUCCESS_RATE				= 132,

	BUFF_INFINITY_ARROW_MASTER						= 143,

	BUFF_ASCENSION									= 105,

	BUFF_FEEL_TIRED									= 107,
	BUFF_FEEL_EXHAUSTED								= 108,

	BUFF_DEATH_STAB_ENHANCED						= 137,
	BUFF_FROZEN_STAB_MASTERED						= 141,
	BUFF_ICE_STORM_ENHANCED							= 146,
	BUFF_EARTH_PRISON								= 147,

	BUFF_POISON_ARROW								= 159,
	BUFF_POISON_ARROW_IMPROVED						= 160,

	BUFF_IRON_DEFENSE								= 134,
	BUFF_IRON_DEFENSE_IMPROVED						= 165,

	BUFF_DRAGON_ROAR_ENHANCED						= 157,
	BUFF_CHAIN_DRIVER_ENHANCED						= 158,

	BUFF_DRAIN_LIFE_ENHANCED						= 145,

	BUFF_BERSERKER_IMPROVED_1						= 150,
	BUFF_BERSERKER_IMPROVED_2						= 151,
	BUFF_BERSERKER_IMPROVED_3						= 152,

	BUFF_BLOOD_HOWLING								= 166,
	BUFF_BLOOD_HOWLING_IMPROVED						= 167,

	BUFF_PENTAGRAM_JEWEL_HALF_SD = 174,
	BUFF_PENTAGRAM_JEWEL_HALF_MP = 175,
	BUFF_PENTAGRAM_JEWEL_HALF_SPEED = 176,
	BUFF_PENTAGRAM_JEWEL_HALF_HP = 177,
	BUFF_PENTAGRAM_JEWEL_STUN = 178,
	BUFF_PENTAGRAM_JEWEL_SLOW = 186,

	BUFF_FIRE_TOWER = 179,
	BUFF_WATER_TOWER = 180,
	BUFF_WIND_TOWER = 181,
	BUFF_EARTH_TOWER = 182,
	BUFF_DARKNESS_TOWER = 183,
	BUFF_RESURRECTION_PENALTY = 184,
	
	BUFF_HORN_OF_UNIRIA = 205,
	BUFF_HORN_OF_DINORANT = 206,
	BUFF_HORN_OF_DARK_HORSE = 207,
	BUFF_HORN_OF_FENRIR = 208,
	BUFF_HORN_OF_DARK_SPIRIT = 232,

	BUFF_PARALYZE = 209,
	BUFF_PARALYZE_IMPROVED = 210,

	BUFF_EVASION = 214,
	BUFF_CIRCLE_SHIELD = 216,

	BUFF_WRATH = 218,
	BUFF_WRATH_IMPROVED_1 = 223,
	BUFF_WRATH_IMPROVED_2 = 224,
	BUFF_WRATH_IMPROVED_3 = 225,
	
	BUFF_BASTION = 238,
	BUFF_HEMORRAGE = 239,
	BUFF_PARALYSIS = 240,
	BUFF_BINDING = 241,
	BUFF_BLINDNESS = 242,

	BUFF_EVOMON_AWAKENING_SUCCESS = 227,
	BUFF_EVOMON_AWAKENING_FAILURE = 228,

	BUFF_NARS_BERSERKER = 229,
	BUFF_NARS_CLONE = 230,
	BUFF_NARS_SPIN = 231,

	BUFF_ARCHANGEL_WILL = 246,

	BUFF_ERRTEL_IMMUNE_I = 243,
	BUFF_ERRTEL_IMMUNE_II = 244,
	BUFF_ERRTEL_BERSERKER_I = 245,

	BUFF_POISONING = 273,
	BUFF_CHILLING = 274,
	BUFF_BLEEDING = 275,
	BUFF_DEADLY_POISONING = 277,
	BUFF_FREEZING = 278,
	BUFF_HEMORRHAGE = 279,

	BUFF_SWITCH_MODE = 292,

	BUFF_DEATHSIDE = 306,

	BUFF_ELITE_BLEEDING = 309,
	BUFF_ELITE_POISON = 310,
	BUFF_ELITE_DAMAGE = 311,
	BUFF_ELITE_SPEED = 312,
	BUFF_ELITE_DEFENSE = 313,

	BUFF_BAT_FLOCK = 315,
	BUFF_DETECTION = 316,

	BUFF_SWORD_WRATH = 324,
	BUFF_SWORD_WRATH_STRENGTHEN = 327,
	BUFF_SWORD_WRATH_MASTERY = 328,

	BUFF_SOLID_PROTECTION_EFFECT = 333,
};

enum BuffOption
{
	BUFF_OPTION_NONE = 0,

	BUFF_OPTION_INCREASE_ATTACK_SPEED				= 1,
	BUFF_OPTION_INCREASE_ATTACK_DAMAGE				= 2,
	BUFF_OPTION_INCREASE_DEFENSE					= 3,
	BUFF_OPTION_INCREASE_MAXIMUM_LIFE				= 4,
	BUFF_OPTION_INCREASE_MAXIMUM_MANA				= 5,
	BUFF_OPTION_INCREASE_EXPERIENCE					= 6,
	BUFF_OPTION_INCREASE_DROP_RATE					= 7,
	BUFF_OPTION_EXPERIENCE_DISABLED					= 8,
	BUFF_OPTION_INCREASE_STRENGTH					= 9,
	BUFF_OPTION_INCREASE_AGILITY					= 10,
	BUFF_OPTION_INCREASE_VITALITY					= 11,
	BUFF_OPTION_INCREASE_ENERGY						= 12,
	BUFF_OPTION_INCREASE_LEADERSHIP					= 13,
	BUFF_OPTION_INCREASE_ATTACK_POWER				= 14,
	BUFF_OPTION_INCREASE_MAGIC_POWER				= 15,
	BUFF_OPTION_ALLOW_MOBILITY						= 16, // Seal of mobility
	BUFF_OPTION_INCREASE_CURSE_DAMAGE = 17,
	BUFF_OPTION_UNK_18 = 18,
	BUFF_OPTION_UNK_19 = 19,
	BUFF_OPTION_UNK_20 = 20,
	BUFF_OPTION_UNK_21 = 21,
	BUFF_OPTION_MIN_WIZARDY							= 22,
	BUFF_OPTION_MAX_WIZARDY							= 23,
	
	BUFF_OPTION_INCREASE_SD_RECOVERY_RATE			= 26,
	BUFF_OPTION_INCREASE_AG_RECOVERY_RATE			= 27,
	BUFF_OPTION_INCREASE_HP_RECOVERY_ADD			= 28,
	BUFF_OPTION_INCREASE_MP_RECOVERY_ADD			= 29,
	BUFF_OPTION_INCREASE_SD_RECOVERY_ADD			= 30,
	BUFF_OPTION_INCREASE_AG_RECOVERY_ADD			= 31,
	BUFF_OPTION_HP_MUL								= 32,
	BUFF_OPTION_MP_MUL								= 33,
	BUFF_OPTION_SD_MUL								= 34,
	BUFF_OPTION_AG_MUL								= 35,
	BUFF_OPTION_HP_DIV								= 36,
	BUFF_OPTION_MP_DIV								= 37,
	BUFF_OPTION_SD_DIV								= 38,
	BUFF_OPTION_AG_DIV								= 39,
	BUFF_OPTION_UNK_40 = 40,
	BUFF_OPTION_UNK_41 = 41,
	BUFF_OPTION_UNK_42 = 42,
	BUFF_OPTION_UNK_43 = 43,
	BUFF_OPTION_UNK_44 = 44,
	BUFF_OPTION_UNK_45 = 45,
	BUFF_OPTION_UNK_46 = 46,
	BUFF_OPTION_UNK_47 = 47,
	BUFF_OPTION_UNK_48 = 48,
	BUFF_OPTION_UNK_49 = 49,
	BUFF_OPTION_UNK_50 = 50,
	BUFF_OPTION_INCREASE_DEFENSE_PERCENT			= 52,

	BUFF_OPTION_AUTOMATIC_HP_RECOVERY = 53,
	BUFF_OPTION_AUTOMATIC_MP_RECOVERY = 54,

	BUFF_OPTION_INCREASE_CRITICAL_DAMAGE_RATE		= 55,
	BUFF_OPTION_INCREASE_EXE_DAMAGE_RATE			= 56,
	BUFF_OPTION_INCREASE_CRITICAL_DAMAGE			= 57,
	BUFF_OPTION_INCREASE_EXE_DAMAGE					= 58,
	BUFF_OPTION_DAMAGE_REFLECTION_RATE				= 59,
	BUFF_OPTION_IGNORE_RATE							= 60,
	BUFF_OPTION_INCREASE_DEFENSE_SUCCESS_RATE		= 61,
	BUFF_OPTION_IGNORE_BASE_DEFENSE = 62,
	BUFF_OPTION_DECREASE_DEFENSE_PERCENT			= 63,
	BUFF_OPTION_INCREASE_ZEN_DROP					= 64,
	BUFF_OPTION_UNK_65 = 65,
	BUFF_OPTION_INCREASE_BOOST_STAMINA				= 66,
	BUFF_OPTION_INCREASE_BOOST_SD					= 67,
	BUFF_OPTION_INCREASE_EXPERIENCE_PARTY			= 68,
	BUFF_OPTION_VITALITY_POTION = 69,
	BUFF_OPTION_INCREASE_MAXIMUM_SD					= 70,
	BUFF_OPTION_INCREASE_MAXIMUM_STAMINA			= 71,
	BUFF_OPTION_SLEEP								= 72,
	BUFF_OPTION_FITNESS								= 73,
	BUFF_OPTION_UNK_74 = 74,
	BUFF_OPTION_UNK_75 = 75,
	BUFF_OPTION_INCREASE_DAMAGE_DECREASE			= 76,
	BUFF_OPTION_UNK_77 = 77,
	BUFF_OPTION_UNK_78 = 78,
	BUFF_OPTION_UNK_79 = 79,
	BUFF_OPTION_UNK_80 = 80,
	BUFF_OPTION_UNK_81 = 81,
	BUFF_OPTION_UNK_82 = 82,
	BUFF_OPTION_UNK_83 = 83,
	BUFF_OPTION_UNK_84 = 84,
	BUFF_OPTION_UNK_85 = 85,
	BUFF_OPTION_UNK_86 = 86,
	BUFF_OPTION_UNK_87 = 87,
	BUFF_OPTION_UNK_88 = 88,
	BUFF_OPTION_UNK_89 = 89,
	BUFF_OPTION_UNK_90 = 90,
	BUFF_OPTION_UNK_91 = 91,
	BUFF_OPTION_UNK_92 = 92,
	BUFF_OPTION_UNK_93 = 93,
	BUFF_OPTION_UNK_94 = 94,
	BUFF_OPTION_UNK_95 = 95,
	BUFF_OPTION_UNK_96 = 96,
	BUFF_OPTION_UNK_97 = 97,
	BUFF_OPTION_UNK_98 = 98,
	BUFF_OPTION_UNK_99 = 99,

	/*BUFF OPTION SKILL*/
	BUFF_OPTION_INCREASE_ATTACK_DAMAGE_SKILL		= 100,
	BUFF_OPTION_UNK_101								= 101,
	BUFF_OPTION_MANA_SHIELD							= 102,
	BUFF_OPTION_WEAKNESS							= 103,
	BUFF_OPTION_INNOVATION							= 104,
	BUFF_OPTION_BERSERKER_DAMAGE					= 105,
	BUFF_OPTION_BERSERKER_DEFENSE					= 106,
	BUFF_OPTION_INFINITY_ARROW_DAMAGE				= 107,
	BUFF_OPTION_DECREASE_DEFENSE_SUCCESS_RATE		= 108,
	BUFF_OPTION_GREATER_DAMAGE						= 109,
	BUFF_OPTION_WRATH_DEFENSE						= 110,
	BUFF_OPTION_WRATH_DAMAGE						= 111,


	BUFF_OPTION_DARKNESS_DECREASE					= 114,
	BUFF_OPTION_WEAKNESS_ELEMENTAL					= 115,
	BUFF_OPTION_INNOVATION_ELEMENTAL				= 116,
	BUFF_OPTION_ELITE_DAMAGE_REDUCTION				= 117,
	BUFF_OPTION_ELITE_ATTACK_SPEED_REDUCTION		= 118,
	BUFF_OPTION_ELITE_DEFENSE_REDUCTION				= 119,
	BUFF_OPTION_UNK_120 = 120,
	BUFF_OPTION_CIRCLE_SHIELD = 121,
	BUFF_OPTION_WEAKNESS_ELEMENTAL_PERCENT			= 122,
	BUFF_OPTION_INNOVATION_ELEMENTAL_PERCENT		= 123,
	BUFF_OPTION_WEAKNESS_PERCENT					= 124,
	BUFF_OPTION_INNOVATION_PERCENT					= 125,
	BUFF_OPTION_DEMOLISH_DAMAGE_DECREASE = 126,
	BUFF_OPTION_UNK_127 = 127,
	BUFF_OPTION_UNK_128 = 128,
	BUFF_OPTION_UNK_129 = 129,
	BUFF_OPTION_INCREASE_ALL_STATS					= 130,
	BUFF_OPTION_UNK_131 = 131,
	BUFF_OPTION_DECREASE_ATTACK_SUCCESS_RATE		= 132,
	BUFF_OPTION_UNK_133 = 133,
	BUFF_OPTION_UNK_134 = 134,
	BUFF_OPTION_UNK_135 = 135,
	BUFF_OPTION_UNK_136 = 136,
	BUFF_OPTION_UNK_137 = 137,
	BUFF_OPTION_UNK_138 = 138,
	BUFF_OPTION_UNK_139 = 139,
	BUFF_OPTION_UNK_140 = 140,
	BUFF_OPTION_UNK_141 = 141,
	BUFF_OPTION_UNK_142 = 142,
	BUFF_OPTION_UNK_143 = 143,
	BUFF_OPTION_UNK_144 = 144,
	BUFF_OPTION_UNK_145 = 145,
	BUFF_OPTION_UNK_146 = 146,
	BUFF_OPTION_UNK_147 = 147,
	BUFF_OPTION_UNK_148 = 148,
	BUFF_OPTION_UNK_149 = 149,
	BUFF_OPTION_UNK_150 = 150,
	BUFF_OPTION_UNK_151 = 151,
	BUFF_OPTION_UNK_152 = 152,
	BUFF_OPTION_UNK_153 = 153,
	BUFF_OPTION_UNK_154 = 154,

	BUFF_OPTION_DEFENSE_REDUCE = 155,
	BUFF_OPTION_ATTACK_SPEED_REDUCE = 156,

	BUFF_OPTION_INCREASES_MP_CONSUMPTION = 157,
	BUFF_OPTION_INCREASES_AG_CONSUMPTION = 158,

	BUFF_OPTION_BASIC_DEFENSE = 159,
	BUFF_OPTION_SOLID_PROTECTION_DAMAGE_TRANSFER = 160,
	BUFF_OPTION_SOLID_PROTECTION_SHIELD_DEFENSE = 161,

	BUFF_OPTION_DECREASE_MAXIMUM_HP = 162,
};

#endif