/*
*
* Copyright (C) 2008-2017 Dimension Gamers <http://www.dimensiongamers.net>
*
* File: "IllusionTempleDef.h"
*
*/
#ifndef ILLUSION_TEMPLE_DEF_H
#define ILLUSION_TEMPLE_DEF_H

#define MAX_ILLUSION_TEMPLE_GROUND			6

enum IllusionTempleState
{
	ILLUSION_TEMPLE_STATE_NONE,
	ILLUSION_TEMPLE_STATE_OPEN,
	ILLUSION_TEMPLE_STATE_STANDBY,
	ILLUSION_TEMPLE_STATE_PLAYING,
	ILLUSION_TEMPLE_STATE_PLAYEND,
	ILLUSION_TEMPLE_STATE_MAX
};

enum IllusionTempleTeam
{
	ILLUSION_TEMPLE_TEAM_BLUE,
	ILLUSION_TEMPLE_TEAM_RED
};

static const EventCommonGroundData m_IllusionTempleData[MAX_ILLUSION_TEMPLE_GROUND] =
{
	WORLD_ILLUSION_TEMPLE_1,	142,
	WORLD_ILLUSION_TEMPLE_2,	143,		
	WORLD_ILLUSION_TEMPLE_3,	144,		
	WORLD_ILLUSION_TEMPLE_4,	145,		
	WORLD_ILLUSION_TEMPLE_5,	146,		
	WORLD_ILLUSION_TEMPLE_6,	147
};

#endif