/*
*
* Copyright (C) 2008-2017 Dimension Gamers <http://www.dimensiongamers.net>
*
* File: "ItemBagDef.h"
*
*/

#ifndef ITEM_BAG_DEF_H
#define ITEM_BAG_DEF_H

enum ItemBagType
{
	ITEM_BAG_ITEM,
	ITEM_BAG_MONSTER,
	ITEM_BAG_MISC,
	ITEM_BAG_MIX,
	ITEM_BAG_WORLD,
	ITEM_BAG_NPC_TALK,
	ITEM_BAG_INVENTORY_ITEM,
	ITEM_BAG_MONSTER_RATE,
	ITEM_BAG_EVENT,
	ITEM_BAG_WORLD_2,
	ITEM_BAG_ZONE,
	ITEM_BAG_GROUP_ITEM,
	ITEM_BAG_GROUP_MONSTER,
	ITEM_BAG_MONSTER_ALL,
	ITEM_BAG_MAX_TYPE
};

enum ItemBagSort
{
	ITEM_BAG_SORT_ITEM					= 0,
	ITEM_BAG_SORT_SET					= 1,
	ITEM_BAG_SORT_ANCIENT_SET			= 2,
};

enum ItemBagResult
{
	ITEM_BAG_RESULT_FAIL,
	ITEM_BAG_RESULT_SUCCESS,
	ITEM_BAG_RESULT_LOW_LEVEL,
};

enum ItemBagCreateType
{
	ITEM_BAG_CREATE_TYPE_FLOOR,
	ITEM_BAG_CREATE_TYPE_INVENTORY,
	ITEM_BAG_CREATE_TYPE_MIX,
	ITEM_BAG_CREATE_TYPE_EVENT_REWARD,
	ITEM_BAG_CREATE_TYPE_GREMORY_CASE,
};

enum
{
	ITEM_BAG_FLAG_FIREWORKS				= 1 << 0,
	ITEM_BAG_FLAG_WEIGHT				= 1 << 1,
	ITEM_BAG_FLAG_CLASS					= 1 << 2,
};

enum
{
	ITEM_BAG_ITEM_FLAG_FIREWORKS		= 1 << 0,
	ITEM_BAG_ITEM_FLAG_FIXED_EXCELLENT	= 1 << 1,
};

#define ITEM_BAG_RATE			10000

#endif