#ifndef LABYRINTH_OF_DIMENSIONS_DEF_H
#define LABYRINTH_OF_DIMENSIONS_DEF_H

enum
{
	LABYRINTH_GATE_UP,
	LABYRINTH_GATE_DOWN,
	LABYRINTH_GATE_LEFT,
	LABYRINTH_GATE_RIGHT,
	LABYRINTH_GATE_MAX
};

enum
{
	LABYRINTH_OF_DIMENSIONS_MISSION_STATE_NONE			= 0,
	LABYRINTH_OF_DIMENSIONS_MISSION_STATE_ACTIVE		= 1,
	LABYRINTH_OF_DIMENSIONS_MISSION_STATE_COMPLETE		= 3,
};

enum
{
	LABYRINTH_OF_DIMENSIONS_AREA_ENTRANCE				= 1,
	LABYRINTH_OF_DIMENSIONS_AREA_NORMAL					= 2,
	LABYRINTH_OF_DIMENSIONS_AREA_MISSION				= 3,
	LABYRINTH_OF_DIMENSIONS_AREA_EXIT					= 4,
};

enum
{
	LABYRINTH_OF_DIMENSIONS_GATE_STATE_NONE				= 0,
	LABYRINTH_OF_DIMENSIONS_GATE_STATE_OPEN				= 1,
	LABYRINTH_OF_DIMENSIONS_GATE_STATE_CLOSED			= 2,
};

enum LabyrinthOfDimensionsMissionType
{
	LABYRINTH_OF_DIMENSIONS_MISSION_TYPE_NONE					= 0,
	LABYRINTH_OF_DIMENSIONS_MISSION_TYPE_KILL_MONSTERS			= 1,
	LABYRINTH_OF_DIMENSIONS_MISSION_TYPE_KILL_MONSTERS_TIME		= 2,
	LABYRINTH_OF_DIMENSIONS_MISSION_TYPE_DO_DAMANGE				= 3,
	LABYRINTH_OF_DIMENSIONS_MISSION_TYPE_ACHIEVE_HELPER_MISSION	= 4,
	LABYRINTH_OF_DIMENSIONS_MISSION_TYPE_KILL_MONSTERS_NOT_HP	= 5,
	LABYRINTH_OF_DIMENSIONS_MISSION_TYPE_KILL_MONSTERS_NOT_MP	= 6,
	LABYRINTH_OF_DIMENSIONS_MISSION_TYPE_TAKE_DAMAGE			= 7,
};

enum
{
	LABYRINTH_OF_DIMENSIONS_RANK_BRONZE = 0,
	LABYRINTH_OF_DIMENSIONS_RANK_SILVER = 1,
	LABYRINTH_OF_DIMENSIONS_RANK_GOLD = 2,
	LABYRINTH_OF_DIMENSIONS_RANK_LEGEND = 3,

	MAX_LABYRINTH_OF_DIMENSIONS_RANK
};

enum
{
	LABYRINTH_OF_DIMENSIONS_LEAGUE_STATE_BRONZE = 0,
	LABYRINTH_OF_DIMENSIONS_LEAGUE_STATE_SILVER = 1,
	LABYRINTH_OF_DIMENSIONS_LEAGUE_STATE_GOLD = 2,
	LABYRINTH_OF_DIMENSIONS_LEAGUE_STATE_LEGEND = 3,

	LABYRINTH_OF_DIMENSIONS_LEAGUE_STATE_MAX
};

#define LABYRINTH_MISSION_MAX			6
#define LABYRINTH_MISSION_MONSTER_MAX	3
#define MAX_LABYRINTH_LEVEL				41
#define MAX_LABYRINTH_PLAYER_MISSION	5


#define LABYRINTH_OF_DIMENSIONS_SAFE_GATE	533

static const struct LabyrinthOfDimensionsWorldData
{
	world_type world;
	coord_type x;
	coord_type y;
} g_LabyrinthOfDimensionsWorldData[1] = 
{
	{ WORLD_LABYRINTH_OF_DIMENSIONS_BATTLE, 20, 13 },
};

#endif