#ifndef MONSTER_DEF_H
#define MONSTER_DEF_H

#define MONSTER_MAX_AI_ORDER			4

#define MAX_MONSTER_NAME_LENGTH			32

enum MonsterDespawn
{
	MONSTER_DESPAWN_NONE		= 0,
	MONSTER_DESPAWN_TIME		= 1,
	MONSTER_DESPAWN_DIE			= 2,
};

#define AI_CONTROL(function) \
	if ( this->GetAI() && this->GetAI()->function ) \
		return;

#define AI_TO(to, ai) reinterpret_cast<to*>(ai)

enum MonsterReaction
{
	REACTION_REST,
	REACTION_MOVE,
	REACTION_ATTACK,
	REACTION_ESCAPE,
};

enum
{
	Movement_Normal,
	Movement_Teleport,
};

#define MONSTER_SKILL_ELEMENT_MAX		5

struct SkillElement
{
	void Reset()
	{
		this->SetValue(0.0f);
		this->SetTime(0);
	}

	DECLARE_FLOAT(Value);
	DECLARE_PROPERTY(int32, Time);
};

#define MAX_MONSTER_SPECIAL_SKILL			20

enum MONSTER_AI_ELEMENT_STATE
{
	MONSTER_AI_ELEMENT_NORMAL,
	MONSTER_AI_ELEMENT_MOVE,
	MONSTER_AI_ELEMENT_ATTACK,
	MONSTER_AI_ELEMENT_HEAL,
	MONSTER_AI_ELEMENT_AVOID,
	MONSTER_AI_ELEMENT_HELP,
	MONSTER_AI_ELEMENT_SPECIAL,
	MONSTER_AI_ELEMENT_EVENT,
	MONSTER_AI_ELEMENT_MAX
};

enum MONSTER_AI_STATE_TRANSITION_TYPE
{
	MAI_STATE_TRANS_NO_ENEMY = 0x0,
	MAI_STATE_TRANS_IN_ENEMY = 0x1,
	MAI_STATE_TRANS_OUT_ENEMY = 0x2,
	MAI_STATE_TRANS_DIE_ENEMY = 0x3,
	MAI_STATE_TRANS_DEC_HP = 0x4,
	MAI_STATE_TRANS_DEC_HP_PER = 0x5,
	MAI_STATE_TRANS_IMMEDIATELY = 0x6,
	MAI_STATE_TRANS_AGRO_UP = 0x7,
	MAI_STATE_TRANS_AGRO_DOWN = 0x8,
	MAI_STATE_TRANS_GROUP_SOMMON = 0xa,
	MAI_STATE_TRANS_GROUP_HEAL = 0xb,
};

enum MONSTER_AI_STATE_TRANSITION_VALUE_TYPE
{
	MAI_STATE_TRANS_VALUE_ = 0x0,
};

enum MONSTER_AI_ELEMENT_TYPE
{
	MAE_TYPE_COMMON_NORMAL = 0x1,
	MAE_TYPE_MOVE_NORMAL = 0xb,
	MAE_TYPE_MOVE_TARGET = 0xc,
	MAE_TYPE_GROUP_MOVE = 0xd,
	MAE_TYPE_GROUP_MOVE_TARGET = 0xe,
	MAE_TYPE_ATTACK_NORMAL = 0x15,
	MAE_TYPE_ATTACK_AREA = 0x16,
	MAE_TYPE_ATTACK_PENETRATION = 0x17,
	MAE_TYPE_HEAL_SELF = 0x1f,
	MAE_TYPE_HEAL_GROUP = 0x20,
	MAE_TYPE_AVOID_NORMAL = 0x29,
	MAE_TYPE_HELP_HP = 0x33,
	MAE_TYPE_HELP_BUFF = 0x34,
	MAE_TYPE_HELP_TARGET = 0x35,
	MAE_TYPE_SPECIAL = 0x3d,
	MAE_TYPE_SPECIAL_SOMMON = 0x3e,
	MAE_TYPE_SPECIAL_IMMUNE = 0x40,
	MAE_TYPE_SPECIAL_NIGHTMARE_SUMMON = 0x41,
	MAE_TYPE_SPECIAL_WARP = 0x42,
	MAE_TYPE_SPECIAL_SKILLATTACK = 0x43,
	MAE_TYPE_SPECIAL_CHANGEAI = 0x44,
	MAE_TYPE_EVENT = 0x47,
};

#define MAX_AI_STATE			8
#define MAX_AI_PRIORITY			30

#define MAX_AI_STATE_RANGE(x) ( ( (x)< 0)?FALSE:((x) > MAX_AI_STATE-1 )? false : true )

#define NIXIES_LAKE_BOSS_SKILL_ID_NORMAL				117
#define NIXIES_LAKE_BOSS_SKILL_ID_ENERGY_SPHERE			118
#define NIXIES_LAKE_BOSS_SKILL_ID_ICE_RAIN				119
#define NIXIES_LAKE_BOSS_SKILL_ID_ICE_BREATH			120
#define NIXIES_LAKE_BOSS_SKILL_ID_ICE_BOOM				121
#define NIXIES_LAKE_BOSS_SKILL_ID_MAGIC_CIRCLE			122

#endif