/*
*
* Copyright (C) 2008-2017 Dimension Gamers <http://www.dimensiongamers.net>
*
* File: "QuestDef.h"
*
*/

#ifndef QUESTDEF_H
#define QUESTDEF_H

static const char quest_evolution_string[4][50] = {"None", "Accept", "Clear", "Reset"};

enum
{
	QUEST_EVOLUTION_START_NPC_CLICK = 2,

	QUEST_EVOLUTION_OBJECTIVE_ITEM = 1,
	QUEST_EVOLUTION_OBJECTIVE_MONSTER = 2,
};

#define QUEST_EVOLUTION_PLUS_STAT_MIN_LEVEL		220
#define QUEST_EVOLUTION_MONSTER_COUNT			5
#define QUEST_EVOLUTION_DROP_RATE				10000

enum QuestEvoltuionCompensation
{
	QUEST_EVOLUTION_COMPENSATION_STAT_UP		= 200,
	QUEST_EVOLUTION_COMPENSATION_CHANGE_UP		= 201,
	QUEST_EVOLUTION_COMPENSATION_PLUS_STAT		= 202,
	QUEST_EVOLUTION_COMPENSATION_COMBO_SKILL	= 203,
	QUEST_EVOLUTION_COMPENSATION_MASTER_UP		= 204,
	QUEST_EVOLUTION_COMPENSATION_ALL_STAT_UP	= 205,
	QUEST_EVOLUTION_COMPENSATION_MAJESTIC_UP	= 206,
};

enum QuestEvolutionState
{
	QUEST_EVOLUTION_STATE_NONE,
	QUEST_EVOLUTION_STATE_ACCEPTED,
	QUEST_EVOLUTION_STATE_COMPLETE,
	QUEST_EVOLUTION_STATE_CLEAR,
	MAX_QUEST_EVOLUTION_STATE,

	QUEST_EVOLUTION_STATE_NO_EXIST = 0xFF
};

enum QuestGuidedState
{
	QUEST_GUIDED_STATE_NONE						= 0,
	QUEST_GUIDED_STATE_ACTIVE					= 1,
	QUEST_GUIDED_STATE_COMPLETE					= 2,
	QUEST_GUIDED_STATE_REWARDED					= 3,
	QUEST_GUIDED_STATE_CANCELED					= 3,
};

enum QuestGuidedObjectiveType
{
	QUEST_GUIDED_OBJECTIVE_TYPE_NONE			= 0,
	QUEST_GUIDED_OBJECTIVE_TYPE_ITEM			= 1,
	QUEST_GUIDED_OBJECTIVE_TYPE_MONSTER_KILL	= 2,
	QUEST_GUIDED_OBJECTIVE_TYPE_LEVEL			= 3,
	QUEST_GUIDED_OBJECTIVE_TYPE_QUEST			= 4,
	QUEST_GUIDED_OBJECTIVE_TYPE_REACH_ZONE		= 5,
};

#define QUEST_MU_MAX_REWARD						3

enum QuestMUObjectiveType
{
	QUEST_MU_OBJECTIVE_ITEM							= 1,
	QUEST_MU_OBJECTIVE_MONSTER_KILL					= 2,
	QUEST_MU_OBJECTIVE_LEVEL						= 3,
	QUEST_MU_OBJECTIVE_LOCATION						= 5,
	QUEST_MU_OBJECTIVE_FIND_NPC						= 6,
	QUEST_MU_OBJECTIVE_MONSTER_KILL_MAP				= 8,
	QUEST_MU_OBJECTIVE_CHAOS_CASTLE_CLEAR			= 10,
	QUEST_MU_OBJECTIVE_CHAOS_CASTLE_PLAYER_KILL		= 11,
	QUEST_MU_OBJECTIVE_BLOOD_CASTLE_CLEAR			= 12,
	QUEST_MU_OBJECTIVE_BLOOD_CASTLE_GATE_DESTROY	= 13,
	QUEST_MU_OBJECTIVE_DEVIL_SQUARE_CLEAR			= 14,
	QUEST_MU_OBJECTIVE_DEVIL_SQUARE_POINTS			= 15,
	QUEST_MU_OBJECTIVE_CHAOS_CASTLE_MONSTER_KILL	= 16,
};

enum
{
	QUEST_MU_START_TYPE_LEVEL						= 1,
	QUEST_MU_START_TYPE_NPC							= 2,
};

enum
{
	QUEST_MU_STATE_NONE								= 0,
	QUEST_MU_STATE_ACTIVE							= 1,
	QUEST_MU_STATE_COMPLETED						= 2,
	QUEST_MU_STATE_CANCELLED						= 3,
};

#endif