/*
*
* Copyright (C) 2008-2017 Dimension Gamers <http://www.dimensiongamers.net>
*
* File: "SkillDef.h"
*
*/

#ifndef SKILLDEF_H
#define SKILLDEF_H

#define MAX_SKILL				60
#define SKILL_LOOP(var)			for ( int32 var = 0; var < MAX_SKILL; ++var )

#define MIN_SKILL_TREE_LEVEL	10
#define MAX_SKILL_TREE_MAJESTIC_LEVEL		20
#define MAX_SKILL_TREE_MAJESTIC_LINK		5
#define MAX_SKILL_TREE_MAJESTIC_PASSIVE		4
#define MAX_SKILL_TREE_MAJESTIC_STAT_STEP	3
#define MAX_SKILL_TREE_MAJESTIC_STAT_GROUP	2

enum SkillType
{
	SkillNone = -1,
	SkillNormal = 0,
	SkillMagic = 1,
};

enum
{
	SKILL_NONE					= 0,
	SKILL_POISON				= 1,
	SKILL_METEORITE				= 2,
	SKILL_LIGHTNING				= 3,
	SKILL_FIRE_BALL				= 4,
	SKILL_FLAME					= 5,
	SKILL_TELEPORT				= 6,
	SKILL_ICE					= 7,
	SKILL_TWISTER				= 8,
	SKILL_EVIL_SPIRIT			= 9,
	SKILL_HELL_FIRE				= 10,
	SKILL_POWER_WAVE			= 11,
	SKILL_AQUA_BEAM				= 12,
	SKILL_BLAST					= 13,
	SKILL_INFERNO				= 14,
	SKILL_MASS_TELEPORT			= 15,
	SKILL_MANA_SHIELD			= 16,
	SKILL_ENERGY_BALL			= 17,
	SKILL_DEFENSE				= 18,
	SKILL_FALLING_SLASH			= 19,
	SKILL_LUNGE					= 20,
	SKILL_UPPERCUT				= 21,
	SKILL_CYCLONE				= 22,
	SKILL_SLASH					= 23,
	SKILL_TRIPLE_SHOT			= 24,
	SKILL_UNKNOWN_1				= 25,
	SKILL_HEAL					= 26,
	SKILL_GREATER_DEFENSE		= 27,
	SKILL_GREATER_DAMAGE		= 28,
	SKILL_UNKNOWN_2				= 29,
	SKILL_SUMMON_MONSTER_1		= 30,
	SKILL_SUMMON_MONSTER_2		= 31,
	SKILL_SUMMON_MONSTER_3		= 32,
	SKILL_SUMMON_MONSTER_4		= 33,
	SKILL_SUMMON_MONSTER_5		= 34,
	SKILL_SUMMON_MONSTER_6		= 35,
	SKILL_SUMMON_MONSTER_7		= 36,
	SKILL_UNKNOWN_3				= 37,
	SKILL_DECAY					= 38,
	SKILL_ICE_STORM				= 39,
	SKILL_NOVA					= 40,
	SKILL_TWISTING_SLASH		= 41,
	SKILL_RAGEFUL_BLOW			= 42,
	SKILL_DEATH_STAB			= 43,
	SKILL_CRESCENT_MOON_SLASH	= 44,
	SKILL_MANA_GLAIVE			= 45,
	SKILL_STARFALL				= 46,
	SKILL_IMPALE				= 47,
	SKILL_GREATER_FORTITUDE		= 48,
	SKILL_FIRE_BREATH			= 49,
	SKILL_FLAME_OF_EVIL			= 50, // Monster Normal Skill Animation
	SKILL_ICE_ARROW				= 51,
	SKILL_PENETRATION			= 52,
	SKILL_UNKNOWN_4				= 53,
	SKILL_UNKNOWN_5				= 54,
	SKILL_FIRE_SLASH			= 55,
	SKILL_POWER_SLASH			= 56,
	SKILL_SPIRAL_SLASH			= 57,
	SKILL_NOVA_CHARGE			= 58,
	SKILL_COMBO					= 59,
	SKILL_FORCE					= 60,
	SKILL_FIRE_BURST			= 61,
	SKILL_EARTHSHAKE			= 62,
	SKILL_SUMMON				= 63,
	SKILL_CRITICAL_DAMAGE		= 64,
	SKILL_ELECTRIC_SPARK		= 65,
	SKILL_FORCE_WAVE			= 66,
	SKILL_STERN					= 67,
	SKILL_CANCEL_STERN			= 68,
	SKILL_SWELL_MANA			= 69,
	SKILL_INVISIBILITY			= 70,
	SKILL_CANCEL_INVISIBILITY	= 71,
	SKILL_CANCEL_MAGIC			= 72,
	SKILL_MANA_RAYS				= 73,
	SKILL_FIRE_BLAST			= 74,
	SKILL_UNKNOWN_8				= 75,
	SKILL_PLASMA_STORM			= 76,
	SKILL_INFINITY_ARROW		= 77,
	SKILL_FIRE_SCREAM			= 78,
	SKILL_FIRE_SCREAM_EXPLOSION	= 79,

	SKILL_SUMMON_MONSTER			= 200,
	SKILL_MAGIC_ATTACK_INMUNITY		= 201,
	SKILL_PHYSICAL_ATTACK_INMUNITY	= 202,
	SKILL_POTION_OF_BLESS			= 203,
	SKILL_POTION_OF_SOUL			= 204,

	SKILL_SPELL_OF_PROTECTION		= 210,
	SKILL_SPELL_OF_RESTRICTION		= 211,
	SKILL_SPELL_OF_PURSUIT			= 212,
	SKILL_FREEZE_TIME				= 213,

	SKILL_DRAIN_LIFE				= 214,
	SKILL_CHAIN_LIGHTNING			= 215,
	SKILL_DAMAGE_REFLECTION			= 217,
	SKILL_BERSERKER					= 218,
	SKILL_SLEEP						= 219,
	SKILL_WEAKNESS					= 221,
	SKILL_INNOVATION				= 222,
	SKILL_EXPLOSION					= 223,
	SKILL_REQUIEM					= 224,
	SKILL_POLLUTION					= 225,

	SKILL_LIGHTNING_SHOCK			= 230,
	SKILL_STRIKE_OF_DESTRUCTION		= 232,
	SKILL_EXPANSION_OF_WIZARDY		= 233,
	SKILL_RECOVERY					= 234,
	SKILL_MULTI_SHOT				= 235,
	SKILL_FLAME_STRIKE				= 236,
	SKILL_GIGANTIC_STORM			= 237,
	SKILL_CHAOTIC_DESEIER			= 238,
	SKILL_DOPPLEGANGER_SUICIDE		= 239,

	SKILL_LARGE_RING_BLOWER			= 260,
	SKILL_UPPER_BEAST				= 261,
	SKILL_CHAIN_DRIVE				= 262,
	SKILL_DARK_SIDE					= 263,
	SKILL_DRAGON_LORE				= 264,
	SKILL_DRAGON_SLAYER				= 265,
	SKILL_RED_ARMOR_IGNORE			= 266,
	SKILL_FITNESS					= 267,
	SKILL_DEFENSE_SUCCESS_RATE		= 268,
	SKILL_CHARGE					= 269,
	SKILL_PHOENIX_SHOT				= 270,

	SKILL_BLOOD_STORM				= 344,
	SKILL_CURE						= 425,
	SKILL_PARTY_HEAL				= 426,
	SKILL_POISON_ARROW				= 427,
	SKILL_BLESS						= 430,
	SKILL_SUMMON_SATYROS			= 432,
	SKILL_BLIND						= 461,
	SKILL_EARTH_PRISON				= 495,
	SKILL_IRON_DEFENSE_1			= 521,
	SKILL_IRON_DEFENSE_2			= 632,
	SKILL_BLOOD_HOWLING				= 565,

	SKILL_SPIN_STEP					= 271,
	SKILL_CIRCLE_SHIELD				= 272,
	SKILL_OBSIDIAN					= 273,
	SKILL_MAGIC_PIN					= 274,
	SKILL_CLASH						= 275,
	SKILL_HARSH_STRIKE				= 276,
	SKILL_SHINING_PEAK				= 277,
	SKILL_WRATH						= 278,
	SKILL_BRECHE					= 279,
	SKILL_SPIN_STEP_EXPLOSION		= 280,
	SKILL_MAGIC_PIN_EXPLOSION		= 281,
	SKILL_BURST						= 700,
	SKILL_ARCHANGELS_WILL			= 740,
	SKILL_ILLUSION					= 642,
	SKILL_SHADOW_STEP				= 651,
	SKILL_EVASION					= 652,
	SKILL_RUSH						= 631,
	SKILL_FIRE_BLOW					= 723,
	SKILL_METEOR_STRIKE				= 724,
	SKILL_METEOR_STORM				= 725,
	SKILL_SOUL_SEEKER				= 726,
	SKILL_FOCUS_SHOT				= 727,
	SKILL_FIRE_BEAST				= 729,
	SKILL_AQUA_BEAST				= 730,
	SKILL_ICE_BLOOD					= 731,
	SKILL_FIRE_BLOOD				= 732,
	SKILL_DARK_BLAST				= 733,
	SKILL_METEOR_STRIKE_2			= 734,
	SKILL_EVIL_WIND					= 737,
	SKILL_DARK_PHOENIX_SHOT			= 739,
	SKILL_SPIRIT_HOOK				= 282,
	SKILL_SWORD_WRATH = 1500,
	SKILL_SWORD_BLOW = 1501,
	SKILL_STRONG_BELIEF = 1502,
	SKILL_SOLID_PROTECTION = 1503,
	SKILL_RUSH_KNIGHT = 813,

	SKILL_DARK_PLASMA = 2001,
	SKILL_ICE_BREAK = 2002,
	SKILL_ICE_BLAST = 2003,
	SKILL_FIRE_DEATH = 2004,
	SKILL_BURSTING_FLARE = 2005,

	SKILL_TREE_DURABILITY_REDUCTION_1					= 300,
	SKILL_TREE_DURABILITY_REDUCTION_1_RF				= 578,
	SKILL_TREE_DURABILITY_REDUCTION_2					= 305,
	SKILL_TREE_DURABILITY_REDUCTION_2_RF				= 583,
	SKILL_TREE_DURABILITY_REDUCTION_3					= 312,
	SKILL_TREE_DURABILITY_REDUCTION_3_RF				= 590,

	SKILL_TREE_DEFENSE_1								= 309,
	SKILL_TREE_DEFENSE_2								= 587,

	SKILL_TREE_DEFENSE_SUCCESS_RATE_PVP_INCREASE_1		= 301,
	SKILL_TREE_DEFENSE_SUCCESS_RATE_PVP_INCREASE_2		= 579,
	SKILL_TREE_INCREASE_MAX_SHIELD_1					= 302,
	SKILL_TREE_INCREASE_MAX_SHIELD_2					= 580,
	SKILL_TREE_INCREASE_MAX_LIFE_1						= 334,
	SKILL_TREE_INCREASE_MAX_LIFE_2						= 600,
	SKILL_TREE_INCREASE_MAX_MANA_1						= 338,
	SKILL_TREE_INCREASE_MAX_MANA_2						= 601,

	SKILL_TREE_WIZARDY_MIN_INCREASE						= 405,
	SKILL_TREE_WIZARDY_AND_CURSE_INCREASE				= 457,
	SKILL_TREE_WIZARDY_AND_CURSE_MIN_INCREASE			= 471,

	SKILL_TREE_WIZARD_INCREASE_1						= 386,
	SKILL_TREE_WIZARD_INCREASE_2						= 488,

	SKILL_TREE_AUTOMATIC_MANA_RECOVERY_1				= 303,
	SKILL_TREE_AUTOMATIC_MANA_RECOVERY_2				= 581,

	SKILL_TREE_AUTOMATIC_STAMINA_RECOVERY_1				= 310,
	SKILL_TREE_AUTOMATIC_STAMINA_RECOVERY_2				= 588,

	SKILL_TREE_ATTACK_SUCCESS_RATE_INCREASE_1			= 325,
	SKILL_TREE_ATTACK_SUCCESS_RATE_INCREASE_2			= 599,

	SKILL_TREE_ATTACK_SUCCESS_RATE_PVP_INCREASE_1		= 347,
	SKILL_TREE_ATTACK_SUCCESS_RATE_PVP_INCREASE_2		= 603,

	SKILL_TREE_ATTACK_DAMAGE_MIN_1						= 361,
	SKILL_TREE_ATTACK_DAMAGE_MIN_2						= 442,
	SKILL_TREE_ATTACK_DAMAGE_MIN_3						= 607,

	SKILL_TREE_WEAPON_MASTERY_1							= 335,
	SKILL_TREE_WEAPON_MASTERY_2							= 421,
	SKILL_TREE_WEAPON_MASTERY_3							= 485,
	SKILL_TREE_WEAPON_MASTERY_4							= 513,
	SKILL_TREE_WEAPON_MASTERY_5							= 557,
	SKILL_TREE_WEAPON_MASTERY_6 = 789,

	SKILL_TREE_MONSTER_DIE_GIVE_LIFE_1					= 359,
	SKILL_TREE_MONSTER_DIE_GIVE_LIFE_2					= 606,

	SKILL_TREE_MONSTER_DIE_GIVE_MANA_1					= 362,
	SKILL_TREE_MONSTER_DIE_GIVE_MANA_2					= 608,

	SKILL_TREE_MONSTER_DIE_GIVE_SHIELD_1				= 358,
	SKILL_TREE_MONSTER_DIE_GIVE_SHIELD_2				= 605,

	SKILL_TREE_SHIELD_RECOVERY_INCREASE_1				= 306,
	SKILL_TREE_SHIELD_RECOVERY_INCREASE_2				= 584,

	SKILL_TREE_FIST_WEAPON_ATTACK_DAMAGE				= 568,
	SKILL_TREE_FIST_WEAPON_DOUBLE_DAMAGE				= 571,

	SKILL_TREE_ONE_HAND_STAFF_WIZARD_DAMAGE				= 397,
	SKILL_TREE_ONE_HAND_STAFF_SPEED						= 400,

	SKILL_TREE_TWO_HAND_STAFF_WIZARD_DAMAGE				= 398,
	SKILL_TREE_TWO_HAND_STAFF_PVP_DAMAGE				= 401,

	SKILL_TREE_ONE_HAND_SWORD_ATTACK_DAMAGE				= 349,
	SKILL_TREE_ONE_HAND_SWORD_SPEED						= 353,

	SKILL_TREE_TWO_HAND_SWORD_ATTACK_DAMAGE				= 348,
	SKILL_TREE_TWO_HAND_SWORD_PVP_DAMAGE				= 352,

	SKILL_TREE_MACE_ATTACK_DAMAGE						= 350,

	SKILL_TREE_SPEAR_ATTACK_DAMAGE						= 351,
	SKILL_TREE_SPEAR_DOUBLE_DAMAGE						= 355,

	SKILL_TREE_CROSSBOW_ATTACK_DAMAGE					= 436,
	SKILL_TREE_CROSSBOW_PVP_DAMAGE						= 439,

	SKILL_TREE_STICK_ATTACK_DAMAGE						= 465,
	SKILL_TREE_STICK_PVP_DAMAGE							= 467,

	SKILL_TREE_SCEPTER_ATTACK_DAMAGE					= 527,
	SKILL_TREE_SCEPTER_PVP_DAMAGE						= 531,
	SKILL_TREE_SCEPTER_DARK_SPIRIT_DAMAGE				= 529,
	SKILL_TREE_SCEPTER_COMMAND							= 533,

	SKILL_TREE_BOW_ATTACK_DAMAGE						= 435,
	SKILL_TREE_BOW_SPEED								= 438,

	SKILL_TREE_BOOK_CURSE_DAMAGE						= 466,
	SKILL_TREE_BOOK_SPEED								= 468,

	SKILL_TREE_SHIELD_DEFENSE_1							= 399,
	SKILL_TREE_SHIELD_DEFENSE_2							= 437,
	SKILL_TREE_SHIELD_DEFENSE_3							= 528,

	SKILL_TREE_HORSE_DEFENSE							= 510,

	SKILL_TREE_FITNRESS_STRENGTHENER					= 573,

	SKILL_TREE_SUMMONED_MONSTER_INCREASE_HP				= 415,
	SKILL_TREE_SUMMONED_MONSTER_INCREASE_DEFENSE		= 419,

	SKILL_TREE_PET_REDUCTION_HP							= 535,

	SKILL_TREE_DARK_SPIRIT_STRENGTHENER_1				= 526,
	SKILL_TREE_DARK_SPIRIT_STRENGTHENER_2				= 530,
	SKILL_TREE_DARK_SPIRIT_STRENGTHENER_3				= 534,

	SKILL_TREE_MANA_REDUCTION_1							= 357,
	SKILL_TREE_MANA_REDUCTION_2							= 604,

	SKILL_TREE_AUTOMATIC_LIFE_RECOVERY_1				= 307,
	SKILL_TREE_AUTOMATIC_LIFE_RECOVERY_2				= 585,

	SKILL_TREE_ADD_ARMOR_SET_BONUS1 = 315,
	SKILL_TREE_ADD_ARMOR_SET_BONUS2 = 593,
	SKILL_TREE_ADD_REFLECT_DAMAGE1 = 316,
	SKILL_TREE_ADD_REFLECT_DAMAGE2 = 594,
	SKILL_TREE_ADD_ENERGY1 = 317,
	SKILL_TREE_ADD_ENERGY2 = 595,
	SKILL_TREE_ADD_ENERGY3 = 814,
	SKILL_TREE_ADD_VITALITY1 = 318,
	SKILL_TREE_ADD_VITALITY2 = 596,
	SKILL_TREE_ADD_VITALITY3 = 815,
	SKILL_TREE_ADD_DEXTERITY1 = 319,
	SKILL_TREE_ADD_DEXTERITY2 = 597,
	SKILL_TREE_ADD_DEXTERITY3 = 816,
	SKILL_TREE_ADD_STRENGTH1 = 320,
	SKILL_TREE_ADD_STRENGTH2 = 598,
	SKILL_TREE_ADD_STRENGTH3 = 817,

	SKILL_TREE_ADD_DK_WING_DEFENSE = 322,
	SKILL_TREE_ADD_DK_WING_DAMAGE = 324,
	SKILL_TREE_ADD_MAX_PHYSI_DAMAGE1 = 364,
	SKILL_TREE_ADD_MAX_PHYSI_DAMAGE2 = 443,
	SKILL_TREE_ADD_MAX_PHYSI_DAMAGE3 = 609,
	SKILL_TREE_ADD_CRITICAL_DAMAGE_RATE1 = 366,
	SKILL_TREE_ADD_CRITICAL_DAMAGE_RATE2 = 610,
	SKILL_TREE_ADD_RESTORE_MP_RATE1 = 367,
	SKILL_TREE_ADD_RESTORE_MP_RATE2 = 611,
	SKILL_TREE_ADD_RESTORE_HP_RATE1 = 368,
	SKILL_TREE_ADD_RESTORE_HP_RATE2 = 612,
	SKILL_TREE_ADD_EXCELLENT_DAMAGE_RATE1 = 369,
	SKILL_TREE_ADD_EXCELLENT_DAMAGE_RATE2 = 613,
	SKILL_TREE_ADD_DOUBLE_DAMAGE_RATE1 = 370,
	SKILL_TREE_ADD_DOUBLE_DAMAGE_RATE2 = 614,
	SKILL_TREE_ADD_IGNORE_DEFENSE_RATE1 = 371,
	SKILL_TREE_ADD_IGNORE_DEFENSE_RATE2 = 615,
	SKILL_TREE_ADD_RESTORE_SD_RATE1 = 372,
	SKILL_TREE_ADD_RESTORE_SD_RATE2 = 616,
	SKILL_TREE_ADD_DW_WING_DEFENSE = 375,
	SKILL_TREE_ADD_DW_WING_DAMAGE = 377,
	SKILL_TREE_ADD_MAX_BP1 = 341,

	SKILL_TREE_ADD_COMBO_DAMAGE = 345,

	SKILL_TREE_ADD_NOVA_START_IMPROVED = 395,
	SKILL_TREE_ADD_MAX_MAGIC_DAMAGE1 = 407,
	SKILL_TREE_ADD_NOVA_IMPROVED = 392,

	SKILL_TREE_ADD_FE_WING_DEFENSE = 410,
	SKILL_TREE_ADD_FE_WING_DAMAGE = 412,
	SKILL_TREE_ADD_SUMMON_DAMAGE = 428,
	SKILL_TREE_ADD_PARTY_HEAL_IMPROVED = 429,
	SKILL_TREE_ADD_BLESS_IMPROVED = 433,
	
	SKILL_TREE_ADD_SU_WING_DEFENSE = 446,
	SKILL_TREE_ADD_SU_WING_DAMAGE = 447,

	SKILL_TREE_ADD_SLEEP_IMPROVED = 454,

	SKILL_TREE_ADD_DRAIN_LIFE_IMPROVED = 458,
	SKILL_TREE_ADD_MAX_MAGIC_DAMAGE2 = 473,

	SKILL_TREE_ADD_MG_WING_DEFENSE = 476,
	SKILL_TREE_ADD_MG_WING_DAMAGE = 478,

	SKILL_TREE_ADD_FIRE_SLASH_ENHANCED = 493,

	SKILL_TREE_ADD_DL_WING_DEFENSE = 505,
	SKILL_TREE_ADD_LEADERSHIP = 506,
	SKILL_TREE_ADD_DL_WING_DAMAGE = 507,
	SKILL_TREE_ADD_FIRE_SCREAM_ENHANCED = 520,
	SKILL_TREE_ADD_GREATER_CRITICAL_DAMAGE_EXTENDED = 522,
	SKILL_TREE_ADD_BIRDS_IMPROVED = 523,
	SKILL_TREE_ADD_IRON_DEFENSE_IMPROVED_1 = 524,
	SKILL_TREE_ADD_IRON_DEFENSE_IMPROVED_2 = 633,
	SKILL_TREE_ADD_DARK_SPIRIT_ATTACK_SPEED = 536,
	SKILL_TREE_ADD_DARK_SPIRIT_DOUBLE_DAMAGE_RATE = 538,
	SKILL_TREE_ADD_DARK_SPIRIT_IGNORE_DEFENSE_RATE = 539,
	
	SKILL_TREE_ADD_RF_WING_DEFENSE = 549,
	SKILL_TREE_ADD_RF_WING_DAMAGE = 550,
	
	SKILL_TREE_ADD_DRAGON_SLAYER_IMPROVED = 564,
	SKILL_TREE_ADD_BLOOD_HOWLING_IMPROVED = 567,

	SKILL_TREE_ADD_STEEL_ARMOR_1 = 626,
	SKILL_TREE_ADD_STEEL_ARMOR_2 = 637,
	SKILL_TREE_ADD_STEEL_ARMOR_3 = 646,
	SKILL_TREE_ADD_STEEL_ARMOR_4 = 656,
	SKILL_TREE_ADD_STEEL_ARMOR_5 = 666,
	SKILL_TREE_ADD_STEEL_ARMOR_6 = 673,
	SKILL_TREE_ADD_STEEL_ARMOR_7 = 680,
	SKILL_TREE_ADD_STEEL_ARMOR_8 = 716,
	SKILL_TREE_ADD_STEEL_ARMOR_9 = 759,
	SKILL_TREE_ADD_STEEL_ARMOR_10 = 790,

	SKILL_TREE_ADD_PROTECTION_SHIELD_1 = 623,
	SKILL_TREE_ADD_PROTECTION_SHIELD_2 = 634,
	SKILL_TREE_ADD_PROTECTION_SHIELD_3 = 643,
	SKILL_TREE_ADD_PROTECTION_SHIELD_4 = 653,
	SKILL_TREE_ADD_PROTECTION_SHIELD_5 = 663,
	SKILL_TREE_ADD_PROTECTION_SHIELD_6 = 670,
	SKILL_TREE_ADD_PROTECTION_SHIELD_7 = 677,
	SKILL_TREE_ADD_PROTECTION_SHIELD_8 = 713,
	SKILL_TREE_ADD_PROTECTION_SHIELD_9 = 758,

	SKILL_TREE_ADD_SHIELD_BLOCK_1 = 625,
	SKILL_TREE_ADD_SHIELD_BLOCK_2 = 636,
	SKILL_TREE_ADD_SHIELD_BLOCK_3 = 645,
	SKILL_TREE_ADD_SHIELD_BLOCK_4 = 655,
	SKILL_TREE_ADD_SHIELD_BLOCK_5 = 665,
	SKILL_TREE_ADD_SHIELD_BLOCK_6 = 672,
	SKILL_TREE_ADD_SHIELD_BLOCK_7 = 679,
	SKILL_TREE_ADD_SHIELD_BLOCK_8 = 715,
	SKILL_TREE_ADD_SHIELD_BLOCK_9 = 756,

	SKILL_TREE_ADD_WEAPON_BLOCK_1 = 624,
	SKILL_TREE_ADD_WEAPON_BLOCK_2 = 664,
	SKILL_TREE_ADD_WEAPON_BLOCK_3 = 791,

	SKILL_TREE_ADD_ABSORB_HP_1 = 628,
	SKILL_TREE_ADD_ABSORB_HP_2 = 639,
	SKILL_TREE_ADD_ABSORB_HP_3 = 648,
	SKILL_TREE_ADD_ABSORB_HP_4 = 658,
	SKILL_TREE_ADD_ABSORB_HP_5 = 668,
	SKILL_TREE_ADD_ABSORB_HP_6 = 675,
	SKILL_TREE_ADD_ABSORB_HP_7 = 682,
	SKILL_TREE_ADD_ABSORB_HP_8 = 718,
	SKILL_TREE_ADD_ABSORB_HP_9 = 761,
	SKILL_TREE_ADD_ABSORB_HP_10 = 792,

	SKILL_TREE_ADD_ABSORB_SD_1 = 629,
	SKILL_TREE_ADD_ABSORB_SD_2 = 640,
	SKILL_TREE_ADD_ABSORB_SD_3 = 649,
	SKILL_TREE_ADD_ABSORB_SD_4 = 659,
	SKILL_TREE_ADD_ABSORB_SD_5 = 669,
	SKILL_TREE_ADD_ABSORB_SD_6 = 676,
	SKILL_TREE_ADD_ABSORB_SD_7 = 683,
	SKILL_TREE_ADD_ABSORB_SD_8 = 719,
	SKILL_TREE_ADD_ABSORB_SD_9 = 762,
	SKILL_TREE_ADD_ABSORB_SD_10 = 793,

	SKILL_TREE_ADD_GRAND_MAGIC_IMPROVED = 641,
	SKILL_TREE_ADD_MARKSMAN = 650,
	SKILL_TREE_ADD_BATTLE_MIND = 630,
	SKILL_TREE_ADD_PAIN_OF_CURSE = 660,
	SKILL_TREE_ADD_PARALYZE_IMPROVED = 662,
	
	SKILL_TREE_ADD_GL_WING_DEFENSE = 685,
	SKILL_TREE_ADD_GL_WING_DAMAGE = 686,
	SKILL_TREE_ADD_SPIN_STEP_MASTERY = 690,
	SKILL_TREE_ADD_OBSIDIAN_IMPROVED = 693,
	SKILL_TREE_ADD_BURST = 700,
	SKILL_TREE_ADD_LANCE_IMPROVED = 702,
	SKILL_TREE_ADD_CIRCLE_SHIELD_IMPROVED = 703,
	SKILL_TREE_ADD_SHIELD_IMPROVED = 704,
	SKILL_TREE_ADD_LANCE_MASTERY = 705,
	SKILL_TREE_ADD_CIRCLE_SHIELD_MASTERY = 706,
	SKILL_TREE_ADD_WRATH_IMPROVED = 708,
	SKILL_TREE_ADD_WRATH_MASTERY = 710,
	SKILL_TREE_ADD_RETALIATION_DAMAGE = 711,
	SKILL_TREE_ADD_RAGE_DAMAGE = 712,

	SKILL_RADIANCE_INMUNE_I = 720,
	SKILL_RADIANCE_INMUNE_II = 721,
	SKILL_RADIANCE_WIDENED_I = 722,

	SKILL_TREE_MAXIMUM_VITALITY_BOOST = 743,
	SKILL_TREE_PHOENIX_SHOT_ENHANCED = 745,

	SKILL_POISON_STORM = 1125,
	SKILL_FROZEN_SLAUGHTER = 1126,
	SKILL_BLEEDING_HEAT = 1127,
	SKILL_SHOCK_BOOM = 1128,

	SKILL_MAGIC_ARROW = 283,
	SKILL_PLASMA_BALL = 284,
	SKILL_LIGHTNING_STORM = 285,
	SKILL_BURST_RW = 286,
	SKILL_HASTE_RW = 287,

	SKILL_RUNE_WIZARD_WINGS_DEFENSE_ENHANCEMENT = 754,
	SKILL_RUNE_WIZARD_WINGS_DAMAGE_ENHANCEMENT = 755,

	SKILL_DEATHSIDE = 288,
	SKILL_DARKNESS = 289,

	SKILL_ELITE_MONSTER = 291,

	SKILL_SWORD_INERTIA = 292,
	SKILL_BAT_FLOCK = 293,
	SKILL_PIERCE_ATTACK = 294,
	SKILL_DETECTION = 295,
	SKILL_DEMOLISH = 297,
};

enum
{
	SKILL_SPECIAL_THUNDER_BREAK = 1,
	SKILL_SPECIAL_BLOODY_WIND = 2,
	SKILL_SPECIAL_FIRE_VAMPIRE_RAY = 3,
	SKILL_SPECIAL_TREU = 4,
	SKILL_SPECIAL_RICK_VAMPIRE_TOUCH = 5,

	SKILL_SPECIAL_DARK_ELF_GROUP_CARBON_REPLACEMENT = 6,
	SKILL_SPECIAL_DARK_ELF_GROUP_THERAPY = 7,
	SKILL_SPECIAL_DARK_ELF_GEOMGI = 8,
	SKILL_SPECIAL_BALRAM_DIRECTION_OFF = 9,
	SKILL_SPECIAL_DEATH_SPIRIT_REDUCE_MANA_AG = 10,
	SKILL_SPECIAL_SORAM_PUSH = 11,
	SKILL_SPECIAL_BALGASS_DIRECT_HIT = 12,
	SKILL_SPECIAL_BALGASS_JABEGI = 13,

	SKILL_SPECIAL_KENTAUROS_MULTI_SHOT = 14,
	SKILL_SPECIAL_PERSONA_EVIL_SPIRIT = 15,
	SKILL_SPECIAL_TWIN_TAIL_HAIR_ATTACK = 16,
	SKILL_SPECIAL_DREADFEAR_DREADNOUGHT = 17,

	SKILL_SPECIAL_POISON_1 = 18,
	SKILL_SPECIAL_DOALGAE = 19,
	SKILL_SPECIAL_SUMMONED = 20,
	SKILL_SPECIAL_PUSHING_1 = 21,
	SKILL_SPECIAL_WHARF = 22,
	SKILL_SPECIAL_PRESSURE = 23,
	SKILL_SPECIAL_POWER_WAVE = 24,
	SKILL_SPECIAL_MAYA_HAND_ICE_STORM = 25,
	SKILL_SPECIAL_BROKEN_SHOWER = 26,
	SKILL_SPECIAL_STERN_1 = 27,
	SKILL_SPECIAL_POISON_2 = 28,
	SKILL_SPECIAL_STERN_2 = 29,
	SKILL_SPECIAL_PUSHING_2 = 30,

	SKILL_SPECIAL_RAGE_STRIKE = 31,
	SKILL_SPECIAL_COOLUTIN_POISON = 32,
	SKILL_SPECIAL_BLOW = 33,

	SKILL_SPECIAL_SELUPAN_POISON = 34,
	SKILL_SPECIAL_SELUPAN_FROST_STORM = 35,
	SKILL_SPECIAL_SELUPAN_FROST_SHOCK = 36,
	SKILL_SPECIAL_SELUPAN_FALL = 37,
	SKILL_SPECIAL_SELUPAN_SUMMONS = 38,
	SKILL_SPECIAL_SELUPAN_TREARMENT = 39,
	SKILL_SPECIAL_SELUPAN_FREEZE = 40,
	SKILL_SPECIAL_SELUPAN_TELEPORTED = 41,
	SKILL_SPECIAL_SELUPAN_INVINCIBLE = 42,
	SKILL_SPECIAL_SELUPAN_BERSERKER = 43,

	SKILL_SPECIAL_GAION_1 = 64,
	SKILL_SPECIAL_GAION_GIGANTIC_STORM = 65,
	SKILL_SPECIAL_GAION_FLAME_STRIKE = 66,
	SKILL_SPECIAL_GAION_4 = 67,

	SKILL_SPECIAL_MERCENARY_GUILD_TERCIA_1 = 78,
	SKILL_SPECIAL_MERCENARY_GUILD_TERCIA_2 = 79,
	SKILL_SPECIAL_MERCENARY_GUILD_TERCIA_3 = 80,
	SKILL_SPECIAL_MERCENARY_GUILD_TERCIA_4 = 81,
};

enum SkillSpecialScope
{
	SKILL_SCOPE_TARGET = -1,
	SKILL_SCOPE_RANGE = 0,
	SKILL_SCOPE_AREA = 1,
	SKILL_SCOPE_TARGET_RANGE = 2,
	SKILL_SCOPE_TARGET_CHAIN = 3,
};

enum SkillSpecialTarget
{
	SKILL_TARGET_ENEMY = 1,
	SKILL_TARGET_SELF = 2,
	SKILL_TARGET_ENEMY_GROUP = 3,
	SKILL_TARGET_SELF_GROUP = 4,
	SKILL_TARGET_SELF_2 = 5,
};

enum
{
	SKILL_ELEMENT_STUN,
	SKILL_ELEMENT_MOVE,
	SKILL_ELEMENT_HP,
	SKILL_ELEMENT_MP,
	SKILL_ELEMENT_AG,
	//SKILL_ELEMENT_SD,
	SKILL_ELEMENT_DEFENSE,
	SKILL_ELEMENT_ATTACK,
	SKILL_ELEMENT_DURABILITY,
	SKILL_ELEMENT_SUMMON,
	SKILL_ELEMENT_PUSH,
	SKILL_ELEMENT_STAT_ENERGY,
	SKILL_ELEMENT_STAT_STRENGTH,
	SKILL_ELEMENT_STAT_AGILITY,
	SKILL_ELEMENT_STAT_VITALITY,
	//SKILL_ELEMENT_STAT_LEADERSHIP,
	SKILL_ELEMENT_REMOVE_SKILL,
	SKILL_ELEMENT_RESIST_SKILL,
	SKILL_ELEMENT_IMMUNE_SKILL,
	SKILL_ELEMENT_TELEPORT_SKILL,
	SKILL_ELEMENT_DOUBLE_HP,
	SKILL_ELEMENT_POISON,
	SKILL_ELEMENT_NORMALATTACK,
	SKILL_ELEMENT_INVINCIBLE,

	SKILL_ELEMENT_MAX
};

enum
{
	SKILL_INCDEC_TYPE_NONE = 0,
	SKILL_INCDEC_TYPE_PERCENTINC = 1,
	SKILL_INCDEC_TYPE_PERCENTDEC = 2,
	SKILL_INCDEC_TYPE_CONSTANTINC = 3,
	SKILL_INCDEC_TYPE_CONSTANTDEC = 4,
	SKILL_INCDEC_TYPE_DESCONOCIDO = 5,
	SKILL_INCDEC_TYPE_CYCLE_PERCENT = 6,
	SKILL_INCDEC_TYPE_CYCLE_PERCENTINC = 7,
	SKILL_INCDEC_TYPE_CYCLE_PERCENTDEC = 8,
	SKILL_INCDEC_TYPE_CYCLE_CONSTANT = 9,
	SKILL_INCDEC_TYPE_CYCLE_CONSTANTINC = 10,
	SKILL_INCDEC_TYPE_CYCLE_CONSTANTDEC = 11,
};

#endif