#ifndef TORMENTED_SQUARE_DEF_H
#define TORMENTED_SQUARE_DEF_H


#define MAX_TORMENTED_SQUARE_GROUND			4
#define TORMENTED_SQUARE_MIN_PLAYER			1 // 3
#define TORMENTED_SQUARE_MAX_PLAYER			20
#define TORMENTED_SQUARE_MAX_TEAM			20

#define MAX_TORMENTED_SQUARE_ROUND			6
#define TORMENTED_SQUARE_GROUND_END_TIME	60
#define TORMENTED_SQUARE_OPEN_TIME			5

#define TORMENTED_SQUARE_GATE				505

static const struct TormentedSquareZone
{
	uint16 world;
	uint16 gate;
} g_TormentedSquareZone[MAX_TORMENTED_SQUARE_GROUND] =
{
	{WORLD_TORMENTED_SQUARE_1, 483},
	{WORLD_TORMENTED_SQUARE_2, 484},
	{WORLD_TORMENTED_SQUARE_3, 485},
	{WORLD_TORMENTED_SQUARE_4, 486},
};

static const struct TormentedSquareLevel
{
	int16 min_level;
	int16 max_level;
	bool master;
} g_TormentedSquareLevel[MAX_TORMENTED_SQUARE_GROUND] =
{
	{200, 400, false},
	{400, 500, true},
	{501, 650, true},
	{651, 2000, true},
};

static const struct TormentedSquarePoints
{
	int32 monster_points;
	int32 boss_points;
	int32 final_points;
} g_TormentedSquarePoints[MAX_PARTY_MEMBERS] =
{
	{9500, 9500, 9500},
	{6500, 6500, 13000},
	{5167, 5167, 15500},
	{4250, 4250, 17000},
	{3500, 3500, 17500},
};

/*
Lv.1 	3000000 	10000000
Lv.2 	10000000 	40000000
Lv.3 	20000000 	50000000
Lv.4 	30000000 	100000000
*/

enum TormentedSquareState
{
	TORMENTED_SQUARE_STATE_NONE,
	TORMENTED_SQUARE_STATE_NOTIFY,
	TORMENTED_SQUARE_STATE_OPEN,
	TORMENTED_SQUARE_STATE_PLAYING,
};

enum TormentedSquareGroundState
{
	TORMENTED_SQUARE_GROUND_STATE_NONE,
	TORMENTED_SQUARE_GROUND_STATE_OPEN,
	TORMENTED_SQUARE_GROUND_STATE_STANDBY,
	TORMENTED_SQUARE_GROUND_STATE_PLAYING,
	TORMENTED_SQUARE_GROUND_STATE_END,
};

enum
{
	TORMENTED_SQUARE_RESULT_QUEUE			= 0,
	TORMENTED_SQUARE_RESULT_PARTY_DISBAND	= 1,
	TORMENTED_SQUARE_RESULT_OK				= 2,
	TORMENTED_SQUARE_RESULT_PARTY_LEADER	= 3,

	TORMENTED_SQUARE_RESULT_NOT_OPEN = 8,
	TORMENTED_SQUARE_RESULT_TEAM_MEMBER_JOINED_ANOTHER_ACTIVITY = 11,
	TORMENTED_SQUARE_RESULT_TEAM_MEMBER_PK = 12,
	TORMENTED_SQUARE_RESULT_TEAM_MEMBER_WRONG_LEVEL = 13,
	TORMENTED_SQUARE_RESULT_TEAM_MEMBER_NOT_ACCEPTED = 24,
	TORMENTED_SQUARE_RESULT_PARTY_DISBAND_2 = 25,
	TORMENTED_SQUARE_RESULT_NOT_ENOUGH_PLAYERS = 26,
	TORMENTED_SQUARE_RESULT_MAXIMUM_PLAYERS = 27,
};

enum TormentedSquareQueueState
{
	TORMENTED_SQUARE_QUEUE_STATE_NONE,
	TORMENTED_SQUARE_QUEUE_STATE_STANDBY,
	TORMENTED_SQUARE_QUEUE_STATE_ACCEPT,
	TORMENTED_SQUARE_QUEUE_STATE_CANCEL,
};

/**********************************************************************************************
							SURVIVAL OF THE FITTEST
**********************************************************************************************/
enum TormentedSquareSurvivalStage
{
	TORMENTED_SQUARE_SURVIVAL_STAGE_NONE,
	TORMENTED_SQUARE_SURVIVAL_STAGE_PRELIMINARY,
	TORMENTED_SQUARE_SURVIVAL_STAGE_SEMI_FINAL,
	TORMENTED_SQUARE_SURVIVAL_STAGE_FINAL,
	TORMENTED_SQUARE_SURVIVAL_STAGE_WINNER,
};

enum TormentedSquareSurvivalGroundState
{
	TORMENTED_SQUARE_SURVIVAL_GROUND_STATE_NONE,
	TORMENTED_SQUARE_SURVIVAL_GROUND_STATE_OPEN,
	TORMENTED_SQUARE_SURVIVAL_GROUND_STATE_STANDBY1,
	TORMENTED_SQUARE_SURVIVAL_GROUND_STATE_PLAYING,
	TORMENTED_SQUARE_SURVIVAL_GROUND_STATE_STANDBY2,
	TORMENTED_SQUARE_SURVIVAL_GROUND_STATE_END,
};

#define MAX_TORMENTED_SQUARE_SURVIVAL_STAGE			3
#define MAX_TORMENTED_SQUARE_SURVIVAL_ROUND			15

#define MAX_TORMENTED_SQUARE_RANKING_SEMI_FINAL		40
#define MAX_TORMENTED_SQUARE_RANKING_FINAL			10

#define TORMENTED_SQUARE_SURVIVAL_MIN_TEAM			1
#define TORMENTED_SQUARE_SURVIVAL_MAX_TEAM			10

#define TORMENTED_SQUARE_SURVIVAL_TEAM_SIZE			2

static const uint16 g_TormentedSquareSurvivalDropReward[MAX_TORMENTED_SQUARE_SURVIVAL_STAGE] = { ITEMGET(14, 258), ITEMGET(14, 259), ITEMGET(14, 260) };
static const uint16 g_TormentedSquareSurvivalWinnerReward[MAX_TORMENTED_SQUARE_SURVIVAL_STAGE] = { ITEMGET(14, 259), ITEMGET(14, 260), ITEMGET(13, 277) };

#endif