MuDatabaseWorkerPool MuDatabase;
GameServerDatabaseWorkerPool GameServerDatabase;
MuLogDatabaseWorkerPool MuLogDatabase;
LoginDatabaseWorkerPool LoginDatabase;
MuEditorDatabaseWorkerPool EditorDatabase;